dist: trusty
language: node_js
sudo: required
node_js:
  - '6.9'
services:
  - docker
cache:
  directories:
  - node_modules
before_install:
  - docker run -d -p 2181:2181 -p 3030:3030 -p 8081:8081 -p 8082:8082 -p 8083:8083 -p 9092:9092 -e ADV_HOST=127.0.0.1 landoop/fast-data-dev
  - sudo apt-get update -qq
  - sudo apt-get -y install libsasl2-dev
